### ISSUE TITLE
Error: Duplicate parameter 'e' not allowed in function with default parameter values.

### ISSUE THREAD

**Issue by rj-david** [zodern/minify-js-sourcemaps#38]
We applied this (v5.1.2) in one of our projects and we started to get errors from safari browsers in production

```
Error: Duplicate parameter 'e' not allowed in function with default parameter values.
```

We are reverting back to v4 for now and will do investigations next week. We are still unsure if the error was from our code (incompatible) or the minifier itself.

**Comment by paulincai** [comment]
@zodern @rj-david got the same in Safari (Mac and IOS). Reverting to standard minifier fixes the problem.

![Screen Shot 2023-07-28 at 2 33 41 PM](https://github.com/zodern/minify-js-sourcemaps/assets/26188915/32014bc0-2868-4802-899c-25d8db10a3c7)
![Screen Shot 2023-07-28 at 2 39 40 PM](https://github.com/zodern/minify-js-sourcemaps/assets/26188915/37e2e9c1-3201-45c7-a18c-8b25f93f109b)

**Comment by paulincai** [comment]
Might only be a problem for React projects.


![Screen Shot 2023-07-28 at 3 04 54 PM](https://github.com/zodern/minify-js-sourcemaps/assets/26188915/fee970fa-dff6-4ecb-984d-890554b9c1ac)



 * react-is.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */"use strict";var er="function"==typeof Symbol&&Symbol.for,eo=er?Symbol.for("react.element"):60103,es=er?Symbol.for("react.portal"):60106,eu=er?Symbol.for("react.fragment"):60107,ep=er?Symbol.for("react.strict_mode"):60108,em=er?Symbol.for("react.profiler"):60114,ey=er?Symbol.for("react.provider"):60109,ev=er?Symbol.for("react.context"):60110,eC=er?Symbol.for("react.async_mode"):60111,ew=er?Symbol.for("react.concurrent_mode"):60111,eS=er?Symbol.for("react.forward_ref"):60112,eT=er?Symbol.for("react.suspense"):60113,eP=er?Symbol.for("react.suspense_list"):60120,eO=er?Symbol.for("react.memo"):60115,eE=er?Symbol.for("react.lazy"):60116,eD=er?Symbol.for("react.block"):60121,eM=er?Symbol.for("react.fundamental"):60117,eI=er?Symbol.for("react.responder"):60118,e_=er?Symbol.for("react.scope"):60119;function eR(et){if("object"==typeof et&&null!==et){var en=et.$$typeof;switch(en){case eo:switch(et=et.type){case eC:case ew:case eu:case em:case ep:case eT:return et;default:switch(et=et&&et.$$typeof){case ev:case eS:case eE:case eO:case ey:return et;default:return en}}case es:return en}}}function eA(et){return eR(et)===ew}en.AsyncMode=eC,en.ConcurrentMode=ew,en.ContextConsumer=ev,en.ContextProvider=ey,en.Element=eo,en.ForwardRef=eS,en.Fragment=eu,en.Lazy=eE,en.Memo=eO,en.Portal=es,en.Profiler=em,en.StrictMode=ep,en.Suspense=eT,en.isAsyncMode=function(et){return eA(et)||eR(et)===eC},en.isConcurrentMode=eA,en.isContextConsumer=function(et){return eR(et)===ev},en.isContextProvider=function(et){return eR(et)===ey},en.isElement=function(et){return"object"==typeof et&&null!==et&&et.$$typeof===eo},en.isForwardRef=function(et){return eR(et)===eS},en.isFragment=function(et){return eR(et)===eu},en.isLazy=function(et){return eR(et)===eE},en.isMemo=function(et){return eR(et)===eO},en.isPortal=function(et){return eR(et)===es},en.isProfiler=function(et){return eR(et)===em},en.isStrictMode=function(et){return eR(et)===ep},en.isSuspense=function(et){return eR(et)===eT},en.isValidElementType=function(et){return"string"==typeof et||"function"==typeof et||et===eu||et===ew||et===em||et===ep||et===eT||et===eP||"object"==typeof et&&null!==et&&(et.$$typeof===eE||et.$$typeof===eO||et.$$typeof===ey||et.$$typeof===ev||et.$$typeof===eS||et.$$typeof===eM||et.$$typeof===eI||et.$$typeof===e_||et.$$typeof===eD)},en.typeOf=eR},"react-is.development.js":function et(et,en){}}},"object-assign":{"package.json":function et(et,en,er){er.exports={name:"object-assign",version:"4.1.1"}},"index.js":function et(et,en,er){/*
object-assign
(c) Sindre Sorhus
@license MIT
*/"use strict";var eo=Object.getOwnPropertySymbols,es=Object.prototype.hasOwnProperty,eu=Object.prototype.propertyIsEnumerable;function ep(et){if(null==et)throw TypeError("Object.assign cannot be called with null or undefined");return Object(et)}function em(){try{if(!Object.assign)return!1;var et=new String("abc");if(et[5]="de","5"===Object.getOwnPropertyNames(et)[0])return!1;for(var en={},er=0;er<10;er++)en["_"+String.fromCharCode(er)]=er;var eo=Object.getOwnPropertyNames(en).map(function(et){return en[et]});if("0123456789"!==eo.join(""))return!1;var es={};if("abcdefghijklmnopqrst".split("").forEach(function(et){es[et]=et}),"abcdefghijklmnopqrst"!==Object.keys(Object.assign({},es)).join(""))return!1;return!0}catch(et){return!1}}er.exports=em()?Object.assign:function(et,en){for(var er,em,ey=ep(et),ev=1;ev<arguments.length;ev++){for(var eC in er=Object(arguments[ev]))es.call(er,eC)&&(ey[eC]=er[eC]);if(eo){em=eo(er);for(var ew=0;ew<em.length;ew++)eu.call(er,em[ew])&&(ey[em[ew]]=er[em[ew]])}}return ey}}},"react-redux":{"package.json":function et(et,en,er){er.exports={name:"react-redux",version:"8.1.1",module:"es/index.js",main:"./lib/index.js"}},es:{"index.js":function et(et,en,er){let eo,es,eu,ep,em,ey;er.export({batch:()=>eu}),er.link("use-sync-external-store/shim",{useSyncExternalStore(et){eo=et}},0),er.link("use-sync-external-store/shim/with-selector",{useSyncExternalStoreWithSelector(et){es=et}},1),er.link("./utils/reactBatchedUpdates",{unstable_batchedUpdates(et){eu=et}},2),er.link("./utils/batch",{setBatch(et){ep=et}},3),er.link("./hooks/useSelector",{initializeUseSelector(et){em=et}},4),er.link("./components/connect",{initializeConnect(et){ey=et}},5),er.link("./exports",{"*":"*"},6),em(es),ey(eo),ep(eu)},utils:{"reactBatchedUpdates.js":function et(et,en,er){er.link("react-dom",{unstable_batchedUpdates:"unstable_batchedUpdates"},0)},"batch.js":function et(et,en,er){er.export({setBatch:()=>es,getBatch:()=>eu},!0);let eo=function et(et){et()},es=et=>eo=et,eu=()=>eo},"useSyncExternalStore.js":function et(et,en,er){er.export({notInitialized:()=>eo},!0);let eo=()=>{throw Error("uSES not initialized!")}},"warning.js":function et(et,en,er){er.export({default:()=>eo});function eo(et){"undefined"!=typeof console&&"function"==typeof console.error&&console.error(et);try{throw Error(et)}catch(et){}}},"bindActionCreators.js":function et(et,en,er){er.export({default:()=>eo});function eo(et,en){let er={};for(let eo in et){let es=et[eo];"function"==typeof es&&(er[eo]=(...et)=>en(es(...et)))}return er}},"verifyPlainObject.js":function et(et,en,er){let eo,es;function eu(et,en,er){eo(et)||es(`${er}() in ${en} must return a plain object. Instead received ${et}.`)}er.export({default:()=>eu}),er.link("./isPlainObject",{default(et){eo=et}},0),er.link("./warning",{default(et){es=et}},1)},"isPlainObject.js":function et(et,en,er){er.export({default:()=>eo});function eo(et){if("object"!=typeof et||null===et)return!1;let en=Object.getPrototypeOf(et);if(null===en)return!0;let er=en;for(;null!==Object.getPrototypeOf(er);)er=Object.getPrototypeOf(er);return en===er}},"Subscription.js":function et(et,en,er){let eo;function es(){let et=eo(),en=null,er=null;return{clear(){en=null,er=null},notify(){et(()=>{let et=en;for(;et;)et.callback(),et=et.next})},get(){let et=[],er=en;for(;er;)et.push(er),er=er.next;return et},subscribe(et){let eo=!0,es=er={callback:et,next:null,prev:er};return es.prev?es.prev.next=es:en=es,function et(){eo&&null!==en&&(eo=!1,es.next?es.next.prev=es.prev:er=es.prev,es.prev?es.prev.next=es.next:en=es.next)}}}}er.export({createSubscription:()=>ep}),er.link("./batch",{getBatch(et){eo=et}},0);let eu={notify(){},get:()=>[]};function ep(et,en){let er;let eo=eu;function ep(et){return eC(),eo.subscribe(et)}function em(){eo.notify()}function ey(){eS.onStateChange&&eS.onStateChange()}function ev(){return!!er}function eC(){er||(er=en?en.addNestedSub(ey):et.subscribe(ey),eo=es())}function ew(){er&&(er(),er=void 0,eo.clear(),eo=eu)}let eS={addNestedSub:ep,notifyNestedSubs:em,handleChangeWrapper:ey,isSubscribed:ev,trySubscribe:eC,tryUnsubscribe:ew,getListeners:()=>eo};return eS}},"useIsomorphicLayoutEffect.js":function et(et,en,er){let eo,es;er.export({canUseDOM:()=>eu,useIsomorphicLayoutEffect:()=>ep},!0),er.link("react",{useEffect(et){eo=et},useLayoutEffect(et){es=et}},0);let eu=!!("undefined"!=typeof window&&void 0!==window.document&&void 0!==window.document.createElement),ep=eu?es:eo},"shallowEqual.js":function et(et,en,er){function eo(et,en){return et===en?0!==et||0!==en||1/et==1/en:et!=et&&en!=en}function es(et,en){if(eo(et,en))return!0;if("object"!=typeof et||null===et||"object"!=typeof en||null===en)return!1;let er=Object.keys(et),es=Object.keys(en);if(er.length!==es.length)return!1;for(let es=0;es<er.length;es++)if(!Object.prototype.hasOwnProperty.call(en,er[es])||!eo(et[er[es]],en[er[es]]))return!1;return!0}er.export({default:()=>es})}},hooks:{"useSelector.js":function et(et,en,er){let eo,es,eu,ep,em,ey,ev;er.export({createSelectorHook:()=>eT}),er.export({initializeUseSelector:()=>ew,useSelector:()=>eP},!0),er.link("react",{useCallback(et){eo=et},useDebugValue(et){es=et},useRef(et){eu=et}},0),er.link("./useReduxContext",{createReduxContextHook(et){ep=et},useReduxContext(et){em=et}},1),er.link("../components/Context",{ReactReduxContext(et){ey=et}},2),er.link("../utils/useSyncExternalStore",{notInitialized(et){ev=et}},3);let eC=ev,ew=et=>{eC=et},eS=(et,en)=>et===en;function eT(et=ey){let en=et===ey?em:ep(et);return function et(et,er={}){let{equalityFn:ep=eS,stabilityCheck:em,noopCheck:ey}="function"==typeof er?{equalityFn:er}:er,{store:ev,subscription:ew,getServerState:eT,stabilityCheck:eP,noopCheck:eO}=en(),eE=(eu(!0),eo({[et.name](en){let er=et(en);return er}}[et.name],[et,eP,em])),eD=eC(ew.addNestedSub,ev.getState,eT||ev.getState,eE,ep);return es(eD),eD}}let eP=eT()},"useReduxContext.js":function et(et,en,er){let eo,es;function eu(et=es){return function en(){let en=eo(et);return en}}er.export({createReduxContextHook:()=>eu}),er.export({useReduxContext:()=>ep},!0),er.link("react",{useContext(et){eo=et}},0),er.link("../components/Context",{ReactReduxContext(et){es=et}},1);let ep=eu()},"useDispatch.js":function et(et,en,er){let eo,es,eu;function ep(et=eo){let en=et===eo?es:eu(et);return function et(){let et=en();return et.dispatch}}er.export({createDispatchHook:()=>ep}),er.export({useDispatch:()=>em},!0),er.link("../components/Context",{ReactReduxContext(et){eo=et}},0),er.link("./useStore",{useStore(et){es=et},createStoreHook(et){eu=et}},1);let em=ep()},"useStore.js":function et(et,en,er){let eo,es,eu;function ep(et=eo){let en=et===eo?es:eu(et);return function et(){let{store:et}=en();return et}}er.export({createStoreHook:()=>ep}),er.export({useStore:()=>em},!0),er.link("../components/Context",{ReactReduxContext(et){eo=et}},0),er.link("./useReduxContext",{useReduxContext(et){es=et},createReduxContextHook(et){eu=et}},1);let em=ep()}},components:{"Context.js":function et(et,en,er){let eo,es;er.export({ReactReduxContext:()=>ey},!0),er.link("react",{createContext(et){eo=et},version(et){es=et}},0);let eu=Symbol.for(`react-redux-context-${es}`),ep=globalThis;function em(){let et=ep[eu];return et||(et=eo(null),ep[eu]=et),et}let ey=new Proxy({},new Proxy({},{get(et,en){let er=em();return(et,...eo)=>Reflect[en](er,...eo)}}));er.exportDefault(ey)},"connect.js":function et(et,en,er){let eo,es,eu,ep,em,ey,ev,eC,ew,eS,eT,eP,eO,eE,eD,eM,eI,e_,eR;er.export({initializeConnect:()=>eN},!0),er.link("@babel/runtime/helpers/esm/extends",{default(et){eo=et}},0),er.link("@babel/runtime/helpers/esm/objectWithoutPropertiesLoose",{default(et){es=et}},1),er.link("hoist-non-react-statics",{default(et){eu=et}},2),er.link("react",{default(et){ep=et},useContext(et){em=et},useMemo(et){ey=et},useRef(et){ev=et}},3),er.link("react-is",{isValidElementType(et){eC=et},isContextConsumer(et){ew=et}},4),er.link("../connect/selectorFactory",{default(et){eS=et}},5),er.link("../connect/mapDispatchToProps",{mapDispatchToPropsFactory(et){eT=et}},6),er.link("../connect/mapStateToProps",{mapStateToPropsFactory(et){eP=et}},7),er.link("../connect/mergeProps",{mergePropsFactory(et){eO=et}},8),er.link("../utils/Subscription",{createSubscription(et){eE=et}},9),er.link("../utils/useIsomorphicLayoutEffect",{useIsomorphicLayoutEffect(et){eD=et}},10),er.link("../utils/shallowEqual",{default(et){eM=et}},11),er.link("../utils/warning",{default(et){eI=et}},12),er.link("./Context",{ReactReduxContext(et){e_=et}},13),er.link("../utils/useSyncExternalStore",{notInitialized(et){eR=et}},14);let eA=["reactReduxForwardedRef"],eL=eR,eN=et=>{eL=et},e$=[null,null];function eU(et,en,er){eD(()=>et(...en),er)}function eF(et,en,er,eo,es,eu){et.current=eo,er.current=!1,es.current&&(es.current=null,eu())}function eB(et,en,er,eo,es,eu,ep,em,ey,ev,eC){if(!et)return()=>{};let ew=!1,eS=null,eT=()=>{let et,er;if(ew||!em.current)return;let eT=en.getState();try{et=eo(eT,es.current)}catch(et){er=et,eS=et}er||(eS=null),et===eu.current?ep.current||ev():(eu.current=et,ey.current=et,ep.current=!0,eC())};er.onStateChange=eT,er.trySubscribe(),eT();let eP=()=>{if(ew=!0,er.tryUnsubscribe(),er.onStateChange=null,eS)throw eS};return eP}function ez(et,en){return et===en}function eW(et,en,er,{pure:eC,areStatesEqual:eI=ez,areOwnPropsEqual:eR=eM,areStatePropsEqual:eN=eM,areMergedPropsEqual:eW=eM,forwardRef:eH=!1,context:eV=e_}={}){let eG=eV,eY=eP(et),eK=eT(en),eX=eO(er),eQ=!!et,eZ=et=>{let en=et.displayName||et.name||"Component",er=`Connect(${en})`,eC={shouldHandleStateChanges:eQ,displayName:er,wrappedComponentName:en,WrappedComponent:et,initMapStateToProps:eY,initMapDispatchToProps:eK,initMergeProps:eX,areStatesEqual:eI,areStatePropsEqual:eN,areOwnPropsEqual:eR,areMergedPropsEqual:eW};function eT(en){let er;let[eu,eT,eP]=ey(()=>{let{reactReduxForwardedRef:et}=en,er=es(en,eA);return[en.context,et,er]},[en]),eO=ey(()=>eu&&eu.Consumer&&ew(ep.createElement(eu.Consumer,null))?eu:eG,[eu,eG]),eM=em(eO),eI=!!en.store&&!!en.store.getState&&!!en.store.dispatch,e_=!!eM&&!!eM.store,eR=eI?en.store:eM.store,eN=e_?eM.getServerState:eR.getState,ez=ey(()=>eS(eR.dispatch,eC),[eR]),[eW,eH]=ey(()=>{if(!eQ)return e$;let et=eE(eR,eI?void 0:eM.subscription),en=et.notifyNestedSubs.bind(et);return[et,en]},[eR,eI,eM]),eV=ey(()=>eI?eM:eo({},eM,{subscription:eW}),[eI,eM,eW]),eY=ev(),eK=ev(eP),eX=ev(),eZ=ev(!1);ev(!1);let eJ=ev(!1),e0=ev();eD(()=>(eJ.current=!0,()=>{eJ.current=!1}),[]);let e1=ey(()=>{let et=()=>eX.current&&eP===eK.current?eX.current:ez(eR.getState(),eP);return et},[eR,eP]),e2=ey(()=>{let et=et=>eW?eB(eQ,eR,eW,ez,eK,eY,eZ,eJ,eX,eH,et):()=>{};return et},[eW]);eU(eF,[eK,eY,eZ,eP,eX,eH]);try{er=eL(e2,e1,eN?()=>ez(eN(),eP):e1)}catch(et){throw e0.current&&(et.message+=`
The error may be correlated with this previous error:
${e0.current.stack}

`),et}eD(()=>{e0.current=void 0,eX.current=void 0,eY.current=er});let e5=ey(()=>ep.createElement(et,eo({},er,{ref:eT})),[eT,et,er]),e3=ey(()=>eQ?ep.createElement(eO.Provider,{value:eV},e5):e5,[eO,e5,eV]);return e3}let eP=ep.memo(eT),eO=eP;if(eO.WrappedComponent=et,eO.displayName=eT.displayName=er,eH){let en=ep.forwardRef(function et(et,en){return ep.createElement(eO,eo({},et,{reactReduxForwardedRef:en}))}),es=en;return es.displayName=er,es.WrappedComponent=et,eu(es,et)}return eu(eO,et)};return eZ}er.exportDefault(eW)},"Provider.js":function et(et,en,er){let eo,es,eu,ep,em;function ey({store:et,context:en,children:er,serverState:ey,stabilityCheck:ev="once",noopCheck:eC="once"}){let ew=es(()=>{let en=ep(et);return{store:et,subscription:en,getServerState:ey?()=>ey:void 0,stabilityCheck:ev,noopCheck:eC}},[et,ey,ev,eC]),eS=es(()=>et.getState(),[et]);em(()=>{let{subscription:en}=ew;return en.onStateChange=en.notifyNestedSubs,en.trySubscribe(),eS!==et.getState()&&en.notifyNestedSubs(),()=>{en.tryUnsubscribe(),en.onStateChange=void 0}},[ew,eS]);let eT=en||eu;return eo.createElement(eT.Provider,{value:ew},er)}er.link("react",{default(et){eo=et},useMemo(et){es=et}},0),er.link("./Context",{ReactReduxContext(et){eu=et}},1),er.link("../utils/Subscription",{createSubscription(et){ep=et}},2),er.link("../utils/useIsomorphicLayoutEffect",{useIsomorphicLayoutEffect(et){em=et}},3),er.exportDefault(ey)}},connect:{"selectorFactory.js":function et(et,en,er){let eo,es;er.export({pureFinalPropsSelectorFactory:()=>ep,default:()=>em}),er.link("@babel/runtime/helpers/esm/objectWithoutPropertiesLoose",{default(et){eo=et}},0),er.link("./verifySubselectors",{default(et){es=et}},1);let eu=["initMapStateToProps","initMapDispatchToProps","initMergeProps"];function ep(et,en,er,eo,{areStatesEqual:es,areOwnPropsEqual:eu,areStatePropsEqual:ep}){let em,ey,ev,eC,ew,eS=!1;function eT(es,eu){return ew=er(ev=et(em=es,ey=eu),eC=en(eo,ey),ey),eS=!0,ew}function eP(){return ev=et(em,ey),en.dependsOnOwnProps&&(eC=en(eo,ey)),ew=er(ev,eC,ey)}function eO(){return et.dependsOnOwnProps&&(ev=et(em,ey)),en.dependsOnOwnProps&&(eC=en(eo,ey)),ew=er(ev,eC,ey)}function eE(){let en=et(em,ey),eo=!ep(en,ev);return ev=en,eo&&(ew=er(ev,eC,ey)),ew}function eD(et,en){let er=!eu(en,ey),eo=!es(et,em,en,ey);return(em=et,ey=en,er&&eo)?eP():er?eO():eo?eE():ew}return function et(et,en){return eS?eD(et,en):eT(et,en)}}function em(et,en){let{initMapStateToProps:er,initMapDispatchToProps:es,initMergeProps:em}=en,ey=eo(en,eu),ev=er(et,ey),eC=es(et,ey),ew=em(et,ey);return ep(ev,eC,ew,et,ey)}},"verifySubselectors.js":function et(et,en,er){let eo;function es(et,en){if(et)"mapStateToProps"!==en&&"mapDispatchToProps"!==en||Object.prototype.hasOwnProperty.call(et,"dependsOnOwnProps")||eo(`The selector for ${en} of connect did not specify a value for dependsOnOwnProps.`);else throw Error(`Unexpected value for ${en} in connect.`)}function eu(et,en,er){es(et,"mapStateToProps"),es(en,"mapDispatchToProps"),es(er,"mergeProps")}er.export({default:()=>eu}),er.link("../utils/warning",{default(et){eo=et}},0)},"mapDispatchToProps.js":function et(et,en,er){let eo,es,eu,ep;function em(et){return et&&"object"==typeof et?es(en=>eo(et,en)):et?"function"==typeof et?eu(et,"mapDispatchToProps"):ep(et,"mapDispatchToProps"):es(et=>({dispatch:et}))}er.export({mapDispatchToPropsFactory:()=>em}),er.link("../utils/bindActionCreators",{default(et){eo=et}},0),er.link("./wrapMapToProps",{wrapMapToPropsConstant(et){es=et},wrapMapToPropsFunc(et){eu=et}},1),er.link("./invalidArgFactory",{createInvalidArgFactory(et){ep=et}},2)},"wrapMapToProps.js":function et(et,en,er){let eo;function es(et){return function en(en){let er=et(en);function eo(){return er}return eo.dependsOnOwnProps=!1,eo}}function eu(et){return et.dependsOnOwnProps?!!et.dependsOnOwnProps:1!==et.length}function ep(et,en){return function en(en,{displayName:er}){let eo=function et(et,en){return eo.dependsOnOwnProps?eo.mapToProps(et,en):eo.mapToProps(et,void 0)};return eo.dependsOnOwnProps=!0,eo.mapToProps=function en(en,er){eo.mapToProps=et,eo.dependsOnOwnProps=eu(et);let es=eo(en,er);return"function"==typeof es&&(eo.mapToProps=es,eo.dependsOnOwnProps=eu(es),es=eo(en,er)),es},eo}}er.export({wrapMapToPropsConstant:()=>es,getDependsOnOwnProps:()=>eu,wrapMapToPropsFunc:()=>ep}),er.link("../utils/verifyPlainObject",{default(et){eo=et}},0)},"invalidArgFactory.js":function et(et,en,er){er.export({createInvalidArgFactory:()=>eo});function eo(et,en){return(er,eo)=>{throw Error(`Invalid value of type ${typeof et} for ${en} argument when connecting component ${eo.wrappedComponentName}.`)}}},"mapStateToProps.js":function et(et,en,er){let eo,es,eu;function ep(et){return et?"function"==typeof et?es(et,"mapStateToProps"):eu(et,"mapStateToProps"):eo(()=>({}))}er.export({mapStateToPropsFactory:()=>ep}),er.link("./wrapMapToProps",{wrapMapToPropsConstant(et){eo=et},wrapMapToPropsFunc(et){es=et}},0),er.link("./invalidArgFactory",{createInvalidArgFactory(et){eu=et}},1)},"mergeProps.js":function et(et,en,er){let eo,es,eu;function ep(et,en,er){return eo({},er,et,en)}function em(et){return function en(en,{displayName:er,areMergedPropsEqual:eo}){let es,eu=!1;return function en(en,er,ep){let em=et(en,er,ep);return eu?eo(em,es)||(es=em):(eu=!0,es=em),es}}}function ey(et){return et?"function"==typeof et?em(et):eu(et,"mergeProps"):()=>ep}er.export({defaultMergeProps:()=>ep,wrapMergePropsFunc:()=>em,mergePropsFactory:()=>ey}),er.link("@babel/runtime/helpers/esm/extends",{default(et){eo=et}},0),er.link("../utils/verifyPlainObject",{default(et){es=et}},1),er.link("./invalidArgFactory",{createInvalidArgFactory(et){eu=et}},2)}},"exports.js":function et(et,en,er){let eo,es,eu,ep,em,ey,ev,eC,ew,eS;er.export({Provider:()=>eo,ReactReduxContext:()=>eu,connect:()=>es,useDispatch:()=>ep,createDispatchHook:()=>em,useSelector:()=>ey,createSelectorHook:()=>ev,useStore:()=>eC,createStoreHook:()=>ew,shallowEqual:()=>eS}),er.link("./components/Provider",{default(et){eo=et}},0),er.link("./components/connect",{default(et){es=et}},1),er.link("./components/Context",{ReactReduxContext(et){eu=et}},2),er.link("./hooks/useDispatch",{useDispatch(et){ep=et},createDispatchHook(et){em=et}},3),er.link("./hooks/useSelector",{useSelector(et){ey=et},createSelectorHook(et){ev=et}},4),er.link("./hooks/useStore",{useStore(et){eC=et},createStoreHook(et){ew=et}},5),er.link("./utils/shallowEqual",{default(et){eS=et}},6),er.link("./types",{"*":"*"},7)},"types.js":function et(){}},node_modules:{"react-is":{"package.json":function et(et,en,er){er.exports={name:"react-is",version:"18.2.0",main:"index.js"}},"index.js":function et(et,en,er){"use strict";er.exports=et("./cjs/react-is.production.min.js")},cjs:{"react-is.production.min.js":function et(et,en,er){/**
 * @license React
 * react-is.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.

**Comment by alisnic** [comment]
We have the same problem, reverted for now

**Comment by zodern** [comment]
It seems to be happening in `modules.js`, which has the code from any files imported from node_modules. I've tried adding the npm packages shown in the code from @paulincai, but wasn't able to reproduce the issue. Would someone be willing to share the code from `packages/modules.js` from a development build (you can load the app in the browser, and use the /packages/modules.js file it loads)? As long as you don't have any private code in an npm package, there shouldn't be anything sensitive in it.

**Comment by paulincai** [comment]
Ok @zodern just to reconfirm you want this from a development project that runs with this package ( zodern:standard-minifier-js) or it doesn't matter?

**Comment by zodern** [comment]
It should be a project that encounters this bug, but whether the app currently uses the minifier doesn't really matter.

**Comment by namenotrequired** [comment]
I'm having exactly this bug in a project that only uses Blaze, not React. The error comes from the path `http://localhost:11111/__cordova/476576cde343b948a68be242440e616ecdb06073.js?meteor_js_resource=true`, I've sent it to you @zodern 

For me it's not happening on Safari but it is happening in the cordova-based iOS app on the same device 🤔

**Comment by zodern** [comment]
Several people shared the modules.js, and I've been able to reproduce on LambdaTest with Safari 16.0.0. The issue doesn't happen on my computer with Safari 16.5.1.

**Comment by jdgjsag67251** [comment]
These feel related:
- https://github.com/mishoo/UglifyJS/issues/5776
- https://github.com/swc-project/swc/issues/6819
- https://github.com/terser/terser/issues/1155

**Comment by zodern** [comment]
I released version 5.2.0 which updates to the latest swc version. SWC has had many bug fixes in the minifier so it might have fixed this.

**Comment by paulincai** [comment]
Will give it a try and get back.

**Comment by paulincai** [comment]
I am able to render the web app in all browsers I tried (Chrome, Mac Safari, IOS, Mac Firefox. All seems ok.

**Comment by jdgjsag67251** [comment]
We have also updated but we still see the same error as before (on some iOS devices)

**Comment by paulincai** [comment]
> We have also updated but we still see the same error as before (on some iOS devices)

"some" sounds a bit funny. Can you suggest IOS versions or so. We can try various versions in simulators.

**Comment by jdgjsag67251** [comment]
Sorry, yeah totally. I know it definitely goes wrong on an iPad running version 15.7.9 with Safari 15.6.6

**Comment by paulincai** [comment]
@jdgjsag67251 maybe related to this: https://github.com/meteor/meteor/pull/12838

**Comment by jdgjsag67251** [comment]
@paulincai, hmm, maybe. But that has been an issue in Meteor for some time and this issue only started recently. But even if it is only the legacy bundle, It should still work when using this package, right?

**Comment by rpong** [comment]
We experienced the same error in 5.2.0.

There were several instances of the error, this is one of them:

![Screenshot 2023-11-06 at 2 15 12 PM](https://github.com/zodern/minify-js-sourcemaps/assets/8245271/7d918d09-5681-49d8-ae5a-8fbd6369dd65)

``

**Comment by zodern** [comment]
This should be fixed in version 5.3.0. I'm no longer able to reproduce after enabling swc's compress.unused option.
